server:
  port: 18090
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: 'https://plugin-auth-ofrdfj.us1.zitadel.cloud/oauth/v2/introspect'
          client-id: '320912215601386953'
          client-secret: 'Oi6WQvgYw5XwfACyH3DQWi0jkF47mzS7ZUFy83uODqrQEDAK0wXr41vSDxPT0OTu'
logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug
zitadel:
  client_id: "Asistente"
  client_secret: "klug5LQYdGAHJuGPa5wFfQMN2d0fvjyAo6Q4hQJQctgcXS4q50qqolWHb54eUE1R"
  scope: "openid profile email urn:zitadel:iam:org:project:id:zitadel:aud"
  urltoken: "https://plugin-auth-ofrdfj.us1.zitadel.cloud/oauth/v2/token"
  urluser: "https://plugin-auth-ofrdfj.us1.zitadel.cloud/management/v1/users/human"

zitadel2:
  scope: 'urn:zitadel:iam:org:project:id:320736469398325498:role:project.owner'