server:
  port: 18090
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: 'https://prueba-fnkj2p.us1.zitadel.cloud/oauth/v2/introspect'
          client-id: '321900389899280615'
          client-secret: 'dUZtoNdEAP7e4pF5y6LzgbSerm3gqET63G4uLeTcJd6vwHl4XpsLWsLhKd5emEKv'

zitadel:
  client-id: 321900389899280615
  client-secret: dUZtoNdEAP7e4pF5y6LzgbSerm3gqET63G4uLeTcJd6vwHl4XpsLWsLhKd5emEKv
  redirect-uri: 'http://localhost:18090/callback'


logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug